name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: walls-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: walls-release-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
          retention-days: 30
